# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 96e12bb
_src_path: https://github.com/MartinBernstorff/nimble-python-template
email: martinbernstorff@gmail.com
full_name: Martin Bernstorff
github_username: MartinBernstorff
package_name: rescuetime2gcal
project_name: Rescuetime2Gcal
project_slug: rescuetime2gcal
python_version: '3.11'
release_docker_image: true
release_package: false
