# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3d48a46
_src_path: https://github.com/MartinBernstorff/nimble-python-template
email: martinbernstorff@gmail.com
full_name: Martin Bernstorff
github_username: MartinBernstorff
package_name: chronofile
project_name: chronofile
project_slug: chronofile
python_version: '3.11'
release_docker_image: true
release_package: false
