services:
  app:
    build: .
    volumes:
      - ./config.toml:/app/config.toml
    environment:
      - CONFIG_PATH=/app/config.toml
      - RESCUETIME_API_KEY
      - ACTIVITYWATCH_BASE_URL
      - GCAL_EMAIL
      - GCAL_CLIENT_ID
      - GCAL_CLIENT_SECRET
      - GCAL_REFRESH_TOKEN
      - TEST_CALENDAR_ID
