name: deploy

on:
  workflow_dispatch:
  schedule:
    # Run the workflow every hour
    - cron: "*/15 9-22 * * *"
    - cron: "55 23 * * *"
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: "${{ github.workflow }} - @ ${{ github.ref }}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2

      - name: Restore Docker image cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-${{ hashFiles('dockerfile') }}

      - name: Set environment variables
        run: |
          echo "TEST_CALENDAR_ID=${{ secrets.TEST_CALENDAR_ID }}" >> .env
          echo "GCAL_EMAIL=${{ secrets.GCAL_EMAIL }}" >> .env
          echo "GCAL_CLIENT_ID=${{ secrets.GCAL_CLIENT_ID }}" >> .env
          echo "GCAL_CLIENT_SECRET=${{ secrets.GCAL_CLIENT_SECRET }}" >> .env
          echo "GCAL_REFRESH_TOKEN=${{ secrets.GCAL_REFRESH_TOKEN }}" >> .env

      - name: Build and deploy Docker container image
        shell: bash
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            make docker_deploy
          else
            make docker_smoketest
          fi
