name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Restore Docker image cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: Build Docker container image
        shell: bash
        run: docker build -t docker-action-test .
      - name: Run Docker container
        shell: bash
        run: docker run docker-action-test
