name: Build and run Docker container from Dockerfile every hour

on:
  schedule:
    # Run the workflow every hour
    - cron: "0 * * * *"
  push:
    branches:
      - main

jobs:
  build-and-run-container:
    runs-on: ubuntu-latest

    concurrency:
      group: "${{ github.workflow }} - ${{ matrix.os }} @ ${{ github.ref }}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: docker-action-test
      - name: Run Docker container
        shell: bash
        run: docker run docker-action-test
